### PR TITLE
Port the library to Windows

### PR DESCRIPTION
**Pull request by pesco**
[Opening pull-request early for ongoing discussion.]

Target build environment (quoting @niklashofmann):

> Our Windows build environment for Everbase: Windows 7/8 32/64bit + Visual Studio 2013. Everbase uses cmake.

Tips from @gsliepen:

> I prefer cross-compiling on Linux; install mingw and then run ./configure --host=i686-w64-mingw32; make. It is faster and much less painful than trying to compile an autoconf project on Windows natively. An example of how to cross-compile tinc and the libraries it uses is here: http://tinc-vpn.org/examples/cross-compiling-windows-binary/ Some info about how to get MSVC to link the resulting DLLs is here: http://factisresearch.blogspot.se/2010/08/cross-compiling-dlls-with-linux.html It seems straightforward to me, but I have to admit that I never used MSVC myself, so it might be more complicated in practice.

Issue areas identified so far:
- `inet_ntop` (exists only as 'InetNtop' starting with Vista)
- `poll` (exists only as 'WSAPoll' starting with Vista and has portability problems (see below))
- `select` (usage differences)
- `uname` (does not exist on Windows)
- function return codes and error checks (Windows sockets are unsigned integers)
- `close` and other file descriptor functions do not work on Windows sockets (they are not file descriptors)
- `fcntl` (does not exist on Windows, parts supported by `socketioctl`)
- `readv`/`writev`/`iovec`/`uio.h` (do not exist on Windows)
- `pipe` (does not exist on Windows)
- `interface` is a keyword (syntax errors all over the code where it is used as an identifier)

Link dump:

"HOWTO Create and Deploy a Sample DLL using MinGW"
http://www.mingw.org/wiki/sampleDLL

"Porting Socket Applications to Winsock" (official Winsock documentation)
http://msdn.microsoft.com/en-us/library/ms740096(v=vs.85).aspx

"BSD Sockets Compatibility" (an unofficial guide)
http://tangentsoft.net/wskfaq/articles/bsd-compatibility.html

Portability problems with WSAPoll
http://social.msdn.microsoft.com/Forums/windowsdesktop/en-US/18769abd-fca0-4d3c-9884-1a38ce27ae90/wsapoll-and-nonblocking-connects-to-nonexistent-ports?forum=wsk

'sys/uio.h' and the 'iovec' structure (don't exist on Windows)
http://pubs.opengroup.org/onlinepubs/009695399/basedefs/sys/uio.h.html

Windows equivalent of pipe()
http://msdn.microsoft.com/en-us/library/windows/desktop/aa365152(v=vs.85).aspx

### CODE REVIEW

**Comment by gsliepen** [comment]
On Tue, Aug 26, 2014 at 06:16:03AM -0700, pesco wrote:

> Tips from @gsliepen:
> &gt; I prefer cross-compiling on Linux; install mingw and then run ./configure --host=i686-w64-mingw32; make. It is faster and much less painful than trying to compile an autoconf project on Windows natively. An example of how to cross-compile tinc and the libraries it uses is here: http://tinc-vpn.org/examples/cross-compiling-windows-binary/ Some info about how to get MSVC to link the resulting DLLs is here: http://factisresearch.blogspot.se/2010/08/cross-compiling-dlls-with-linux.html It seems straightforward to me, but I have to admit that I never used MSVC myself, so it might be more complicated in practice.
> 
> Issue areas identified so far:
> - `inet_ntop` (exists only as &#39;InetNtop&#39; starting with Vista)

This could be replaced by getaddrinfo(), but maybe that also doesn't
exist before Vista.

> - `poll` (exists only as &#39;WSAPoll&#39; starting with Vista and has portability problems (see below))
> - `select` (usage differences)

It should be possible to use select() just like on Linux; I never had
problems with it (as long as you stick to the FD_SET/FD_CLEAR etc.
functions, which one should anyway for portable code).

> - `uname` (does not exist on Windows)

Can be replaced by GetComputerName()

> - function return codes and error checks (Windows sockets are unsigned integers)
> - `close` and other file descriptor functions do not work on Windows sockets (they are not file descriptors)

Use closesocket() instead. In tinc, I use closesocket() for sockets
everywhere, and the I just have this in a common header:

#ifndef _WIN32
#define closesocket socket
#endif

> - `fcntl` (does not exist on Windows, parts supported by `socketioctl`)
> - `readv`/`writev`/`iovec`/`uio.h` (do not exist on Windows)

Hm, that's nasty, but it should be possible to rewrite those. I see
readv() and writev() are not used, but sendmsg() and recvmsg() are.

> - `pipe` (does not exist on Windows)

It could be replaced by a TCP socket to itself.

> - `interface` is a keyword (syntax errors all over the code where it is used as an identifier)

Ah, I remember I had that problem in tinc as well, replaced it
everywhere with `iface`.

Hm, I guess there was more to it than I thought...

## 

Met vriendelijke groet / with kind regards,
     Guus Sliepen guus@tinc-vpn.org

**Comment by pesco** [comment]
As it turns out, `inet_ntop` (and `inet_pton`) do exist in Winsock 2 (starting with Vista), docs and error message were just confusing.

So this begs the question, @niklashofmann, would you like it to run on XP? For the moment I'm compiling for Vista just to get as far as possible, so there might be other things I'm unaware of right now that need handling/replacement.

**Comment by coreprocess** [comment]
We do not want to support XP :-)

**Comment by pesco** [comment]
So far so good, most of the small fry and the big chunk of `recvmsg`/`sendmsg` are out of the way. Now it's mainly the `CattaWatch` poll/mainloop abstraction that remains.

TODO:
- `simple-watch.c`
  - get `poll` to work or rewrite to use `select`.
  - provide `pipe` or work around
- make sure all socket function calls are checked for errors properly
  - `if(foo(...) < 0)` is not okay on Windows (because their `SOCKET` is unsigned)
  - `errno` is not set
- call `WSAStartup` and `WSACleanup` in an appropriate place

**Comment by coreprocess** [comment]
awesome!

**Comment by pesco** [comment]
One more thing is the OS-specific interface detection stuff. It isn't required to compile the library (everything except one test builds now) but I think the `CattaServer` might not answer requests without it.

**Comment by pesco** [comment]
The library is designed around knowing all network interfaces, so we need that functionality. Relevant Windows interfaces:
- `GetAdaptersAddresses()` (`iphlpapi.h`)
  http://msdn.microsoft.com/en-us/library/windows/desktop/aa365915(v=vs.85).aspx
- `NotifyIpInterfaceChange()` (`iphlpapi.h`)
  http://msdn.microsoft.com/en-us/library/windows/desktop/aa814450(v=vs.85).aspx

Related but not for us:
- Network List Manager API (C++ / COM)
  http://msdn.microsoft.com/en-us/library/windows/desktop/aa370799(v=vs.85).aspx
  - NLM introduction
    http://msdn.microsoft.com/en-us/library/ee264321(v=vs.85).aspx
- System.Net.NetworkInformation (.NET)
  http://msdn.microsoft.com/en-us/library/system.net.networkinformation.networkchange(v=vs.110).aspx?cs-save-lang=1&cs-lang=cpp

The last test that doesn't compile (`dns-spin-test`) uses the POSIX function `setitimer`.
- Windows timer functions:
  http://msdn.microsoft.com/en-us/library/windows/desktop/ms644906(v=vs.85).aspx
- Someone else's implementation of `setitimer` for a MingW target:
  http://lists-archives.com/git/647612-windows-implement-setitimer-and-sigaction.html

**Comment by pesco** [comment]
> function return codes and error checks (Windows sockets are unsigned integers)

Sensibly, the unsigned `SOCKET` type is only returned by functions that actually create a socket, i.e. `accept` and `socket`. Others like `bind`, `listen`, etc. return an `int` result just like POSIX. Catta doesn't use `accept`, so the only places to check are the `socket` calls in `src/socket.c`:

```
src/socket.c:326:    if ((fd = socket(AF_INET, SOCK_DGRAM, 0)) < 0) {
src/socket.c:390:    if ((fd = socket(AF_INET6, SOCK_DGRAM, 0)) < 0) {
src/socket.c:927:    if ((fd = socket(AF_INET, SOCK_DGRAM, 0)) < 0) {
src/socket.c:967:    if ((fd = socket(AF_INET6, SOCK_DGRAM, 0)) < 0) {
```

In all cases, the `SOCKET` result is assigned to the `int` `fd` before the comparison, so this code should work on Windows.

A question remains what value of `errno`, if any, Windows sets after the socket calls. The documentation makes it sound like they don't set it at all, or just to some dummy, and you always have to use `WSAGetLastError`. I have a suspicion, though, that they might in fact map it in some best-effort manner, like I've done explicitly with `wsa_errno()` for `recvmsg` and friends. One might do some experiments to look into that.

In any case, by far most references to `errno` in the code are just calls to `strerror` for some message, so no semantic harm can come from them. As far as I can see, the only places I need to look at are:

```
src/socket.c:206:        if (errno != EADDRINUSE) {
src/socket.c:462:        if (errno == EINTR)
src/socket.c:465:        if (errno != EAGAIN) {
src/socket.c:689:        if (errno != EAGAIN)
src/socket.c:851:        if (errno != EAGAIN)
```

**Comment by gsliepen** [comment]
On Thu, Sep 04, 2014 at 10:56:30AM -0700, pesco wrote:

> A question remains what value of `errno`, if any, Windows sets after the socket calls. The documentation makes it sound like they don't set it at all, or just to some dummy, and you always have to use `WSAGetLastError`. I have a suspicion, though, that they might in fact map it in some best-effort manner, like I've done explicitly with `wsa_errno()` for `recvmsg` and friends. One might do some experiments to look into that.

I think you should always use WSAGetLastError() for any socket related
function.

> In any case, by far most references to `errno` in the code are just calls to `strerror` for some message, so no semantic harm can come from them. As far as I can see, the only places I need to look at are:
> 
> ```
> src/socket.c:462:        if (errno == EINTR)
> src/socket.c:465:        if (errno != EAGAIN) {
> src/socket.c:689:        if (errno != EAGAIN)
> src/socket.c:851:        if (errno != EAGAIN)
> ```

I use this...

#ifdef _WIN32
extern const char *winerror(int);
#define strerror(x) ((x)>0?strerror(x):winerror(GetLastError()))
#define sockerrno WSAGetLastError()
#define sockstrerror(x) winerror(x)
#define sockwouldblock(x) ((x) == WSAEWOULDBLOCK || (x) == WSAEINTR)
#define sockmsgsize(x) ((x) == WSAEMSGSIZE)
#define sockinprogress(x) ((x) == WSAEINPROGRESS || (x) ==
WSAEWOULDBLOCK)
#define sockinuse(x) ((x) == WSAEADDRINUSE)
#define socknotconn(x) ((x) == WSAENOTCONN)
#else
#define sockerrno errno
#define sockstrerror(x) strerror(x)
#define sockwouldblock(x) ((x) == EWOULDBLOCK || (x) == EINTR)
#define sockmsgsize(x) ((x) == EMSGSIZE)
#define sockinprogress(x) ((x) == EINPROGRESS)
#define sockinuse(x) ((x) == EADDRINUSE)
#define socknotconn(x) ((x) == ENOTCONN)
#endif

## 

Met vriendelijke groet / with kind regards,
     Guus Sliepen guus@tinc-vpn.org

**Comment by pesco** [comment]
> ```
> src/socket.c:206:        if (errno != EADDRINUSE) {
> ```

from `bind`, related to `SO_REUSEADDR`; should not happen due to the workaround in f5e8cf9 and if it did it would only cause a spurious log message.

> ```
> src/socket.c:462:        if (errno == EINTR)
> ```

from `sendmsg`; should not happen on Windows

> ```
> src/socket.c:465:        if (errno != EAGAIN) {
> ```

from `sendmsg`; this is `EWOULDBLOCK` on Windows and possibly other platforms.

> ```
> src/socket.c:689:        if (errno != EAGAIN)
> src/socket.c:851:        if (errno != EAGAIN)
> ```

from `recvmsg`; the comment in the code says this is a Linux-specific case. only semantic difference is whether a log message is generated or not. should not happen on Windows as far as i can see.

**Comment by pesco** [comment]
Initial interface enumeration is performed and looking good but run-time interface/address changes are still to do.

The examples work and network traffic looks as expected.

I changed all the socket-related `strerror(errno)` calls to use `WSAGetLastError`. Finally, there are a few non-essential items left in the code (`git grep XXX`) that can be done whenever.

**Comment by pesco** [comment]
I think it is ready. :) I tested interface change detection by plugging/pulling the virtual network cable of a VirtualBox VM.

Here is my high-level list of non-essential todo items that remain to be done at discretion:
- squelch annoying "lt_fatal candidate for noreturn" warning (MingW)
- why does the dll build complain about -lssp? (even though it works) (MingW)
- `git grep XXX`
- `git grep TODO`
- update the documentation

A note about building with MingW: The resulting DLL depends on MingW runtime DLLs. I just `locate`d these and copied them into the directory with the example `.exe`.

```
/usr/i686-w64-mingw32/lib/libwinpthread-1.dll
/usr/lib/gcc/i686-w64-mingw32/4.9-posix/libgcc_s_sjlj-1.dll
/usr/lib/gcc/i686-w64-mingw32/4.9-posix/libssp-0.dll
```

Note: I don't know what `posix` in the above paths refers to. I also have a `win32` variant but did not try it.

**Comment by pesco** [comment]
Identified and fixed the bug where things would look like they work but then stop: a stupid mistake caused `ioctl()` to silently set blocking I/O on all sockets, especially the fake pipes.

Some other notes:
- Version 2.0.3 of MingW-w64 which is currently distributed with Debian stable is missing the `winpthread` library and thus cannot be used. My dev system has MingW-w64 3.2.0.
- There are bound to be some potential issues with integer sizes when compiling for 64-bit Windows, because Windows likes to use specific-width types everywhere.
- I don't know how to build with the GCC "stack protector" (`ssp`) enabled. Somehow it doesn't find the `libssp` symbols during `make` and refuses to build the DLL.

Therefore, here is how I configure for Windows:

```
./configure --host=i686-w64-mingw32 --enable-tests --disable-stack-protector
```

**Comment by coreprocess** [comment]
:+1:

**Pull request merged**
