### PR TITLE
Stripdown

### PR DESCRIPTION
**Pull request by pesco**
All test programs (`avahi-core/*-test`, `avahi-common/*-test`) compile and run, `make check` reports 3/3 pass.

Examples compile and run, I still want to try them over the network.

### CODE REVIEW

**Comment by coreprocess** [comment]
Nice!
@gsliepen can you perform a review too?
I will review the branch later today.

**Comment by pesco** [comment]
And if you let the examples use the same service type, they actually see each other over the network... ;)

**Comment by coreprocess** [comment]
And if you enable config.publish_no_reverse the example works even in case an avahi daemon is running :-)

**Comment by coreprocess** [comment]
The bundled examples work. The manynodes example of meshlink works too [CFLAGS="-fPIC" is required while building catta]. :+1:

**Comment by coreprocess** [comment]
Can we delete avahi-common/i18n.\* or is it still required?

**Comment by coreprocess** [comment]
Do we need avahi-core/avahi-reflector.c?

**Comment by coreprocess** [comment]
Everything else looks fine to me. @gsliepen what do you think?

**Comment by pesco** [comment]
We can get rid of `i81n.*` easy enough, I just left it in because I was defaulting to minimizing intrusive code changes. I.e. we need to remove the gettext calls in `error.c` before the files can be deleted.

The `avahi-reflector` executable apparently implements a stand-alone version of the reflector functionality also exposed by the daemon. It's used to pass mDNS messages across networks. From avahi-daemon.conf(1):

> `enable-reflector=` Takes a boolean value ("yes" or "no"). If set to "yes" avahi-daemon will reflect incoming mDNS requests to all local network interfaces, effectively allowing clients to browse mDNS/DNS-SD services on all networks connected to the gateway. The gateway is somewhat intelligent and should work with all kinds of mDNS traffic, though some functionality is lost (specifically the unicast reply bit, which is used rarely anyway). Make sure to not run multiple reflectors between the same networks, this might cause them to play Ping Pong with mDNS packets. Defaults to "no".

**Comment by gsliepen** [comment]
On Mon, Aug 18, 2014 at 09:22:18AM -0700, Niklas wrote:

> Nice!
> @gsliepen can you perform a review too?
> I will review the branch later today.

It looks good to me! Some further things that could be done:
- merge the core and common components (both the directories and the
  resulting .so files)
- bootstrap.sh and autogen.sh are not really necessary anymore, running
  autoreconf is sufficient (I checked)
- require a C99 compiler; this can get rid of lots of checks in
  configure.ac, and some #ifdefs in the code.
- s/avahi/catta/ everywhere :)
- port to Windows (should not be too hard, I think it can be done just
  by linking to pthread-win32 and some minor modifications to the socket
  handling routines)

## 

Met vriendelijke groet / with kind regards,
     Guus Sliepen guus@tinc-vpn.org

**Comment by coreprocess** [comment]
@gsliepen: I agree. @pesco: what do you think?
@gsliepen: Thanks for the hints regarding the windows port. I agree, in general it should not be too hard; except the part which deals with the monitoring of the network interfaces. I guess the interface monitor is very os specific.

**Comment by pesco** [comment]
all sounds good to me. nice to hear about autoreconf, i haven't had to use autotools for ages.

the os-specific interface monitoring stuff is indeed in `avahi-core/iface-*.[ch]`.

**Comment by pesco** [comment]
performed the suggestions above, as well as a little directory shuffle that i think fits better with the single-library situation.

i will be out of town tomorrow and Friday. maybe you can review these changes and if you are happy with them i can start on the port(s) on monday. speaking of which, it would be good to know what your windows build environment is like.

**Comment by coreprocess** [comment]
Awesome! I linked it to meshlink successfully. I am happy :+1: 
@gsliepen what do you think?

**Comment by coreprocess** [comment]
Our Windows build environment for Everbase: Windows 7/8 32/64bit + Visual Studio 2013. Everbase uses cmake. Not sure how to deal with autoconf on Windows.

**Comment by gsliepen** [comment]
On Wed, Aug 20, 2014 at 10:23:37AM -0700, Niklas wrote:

> Our Windows build environment for Everbase: Windows 7/8 32/64bit + Visual Studio 2013. Everbase uses cmake. Not sure how to deal with autoconf on Windows.

I prefer cross-compiling on Linux; install mingw and then run
./configure --host=i686-w64-mingw32; make. It is faster and much less
painful than trying to compile an autoconf project on Windows natively.
An example of how to cross-compile tinc and the libraries it uses is
here:

http://tinc-vpn.org/examples/cross-compiling-windows-binary/

Some info about how to get MSVC to link the resulting DLLs is here:

http://factisresearch.blogspot.se/2010/08/cross-compiling-dlls-with-linux.html

It seems straightforward to me, but I have to admit that I never used
MSVC myself, so it might be more complicated in practice.

## 

Met vriendelijke groet / with kind regards,
     Guus Sliepen guus@tinc-vpn.org

**Pull request merged**
